### ISSUE TITLE
unhelpful error message

### ISSUE THREAD

**Issue by harwood-yoha** [pelican-plugins/photos#50] opened 2022-06-22 20:58 UTC
<class 'pelican.plugins.photos.photos.CaptionCache'>
<class 'pelican.plugins.photos.photos.ExifCache'>
<class 'pelican.plugins.photos.photos.ExcludeCache'>
<class 'pelican.plugins.photos.photos.CaptionCache'>
<class 'pelican.plugins.photos.photos.ExifCache'>
<class 'pelican.plugins.photos.photos.ExcludeCache'>
<class 'pelican.plugins.photos.photos.CaptionCache'>
<class 'pelican.plugins.photos.photos.ExifCache'>
<class 'pelican.plugins.photos.photos.ExcludeCache'>
<class 'pelican.plugins.photos.photos.CaptionCache'>
<class 'pelican.plugins.photos.photos.ExifCache'>
<class 'pelican.plugins.photos.photos.ExcludeCache'>
           CRITICAL AttributeError: 'NoneType' object has no attribute 'partition'                 __init__.py:566

**Comment by harwood-yoha** [comment] 2022-06-22 21:12
with debug 

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/__init__.py:562 in main        │
│                                                                                                  │
│   559 │   │   │   watcher = FileSystemWatcher(args.settings, Readers, settings)                  │
│   560 │   │   │   watcher.check()                                                                │
│   561 │   │   │   with console.status("Generating..."):                                          │
│ ❱ 562 │   │   │   │   pelican.run()                                                              │
│   563 │   except KeyboardInterrupt:                                                              │
│   564 │   │   logger.warning('Keyboard interrupt received. Exiting.')                            │
│   565 │   except Exception as e:                                                                 │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/__init__.py:121 in run         │
│                                                                                                  │
│   118 │   │   │   if hasattr(p, 'refresh_metadata_intersite_links'):                             │
│   119 │   │   │   │   p.refresh_metadata_intersite_links()                                       │
│   120 │   │                                                                                      │
│ ❱ 121 │   │   signals.all_generators_finalized.send(generators)                                  │
│   122 │   │                                                                                      │
│   123 │   │   writer = self._get_writer()                                                        │
│   124                                                                                            │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/blinker/base.py:267 in send            │
│                                                                                                  │
│   264 │   │   │   return []                                                                      │
│   265 │   │   else:                                                                              │
│   266 │   │   │   return [(receiver, receiver(sender, **kwargs))                                 │
│ ❱ 267 │   │   │   │   │   for receiver in self.receivers_for(sender)]                            │
│   268 │                                                                                          │
│   269 │   def has_receivers_for(self, sender):                                                   │
│   270 │   │   """True if there is probably a receiver for *sender*.                              │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/blinker/base.py:267 in <listcomp>      │
│                                                                                                  │
│   264 │   │   │   return []                                                                      │
│   265 │   │   else:                                                                              │
│   266 │   │   │   return [(receiver, receiver(sender, **kwargs))                                 │
│ ❱ 267 │   │   │   │   │   for receiver in self.receivers_for(sender)]                            │
│   268 │                                                                                          │
│   269 │   def has_receivers_for(self, sender):                                                   │
│   270 │   │   """True if there is probably a receiver for *sender*.                              │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:1254  │
│ in handle_signal_all_generators_finalized                                                        │
│                                                                                                  │
│   1251 def handle_signal_all_generators_finalized(                                               │
│   1252 │   generators: List[pelican.generators.Generator],                                       │
│   1253 ):                                                                                        │
│ ❱ 1254 │   detect_content_images_and_galleries(generators)                                       │
│   1255 │   resize_photos()                                                                       │
│   1256                                                                                           │
│   1257                                                                                           │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:1248  │
│ in detect_content_images_and_galleries                                                           │
│                                                                                                  │
│   1245 │   │   │   │   generator.pages, generator.translations, generator.hidden_pages           │
│   1246 │   │   │   ):                                                                            │
│   1247 │   │   │   │   detect_content_image(generator, page)                                     │
│ ❱ 1248 │   │   │   │   detect_content_galleries(generator, page)                                 │
│   1249                                                                                           │
│   1250                                                                                           │
│   1251 def handle_signal_all_generators_finalized(                                               │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:1197  │
│ in detect_content_galleries                                                                      │
│                                                                                                  │
│   1194 │   if "gallery" in content.metadata:                                                     │
│   1195 │   │   gallery = content.metadata.get("gallery")                                         │
│   1196 │   │   if gallery.startswith("{photo}") or gallery.startswith("{filename}"):             │
│ ❱ 1197 │   │   │   content.photo_gallery = process_content_galleries(content, gallery)           │
│   1198 │   │   elif gallery:                                                                     │
│   1199 │   │   │   logger.error(f"photos: Gallery tag not recognized: {gallery}")                │
│   1200                                                                                           │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:1164  │
│ in process_content_galleries                                                                     │
│                                                                                                  │
│   1161 │                                                                                         │
│   1162 │   for gallery in galleries:                                                             │
│   1163 │   │   try:                                                                              │
│ ❱ 1164 │   │   │   gallery = Gallery(content, gallery)                                           │
│   1165 │   │   except GalleryNotFound as e:                                                      │
│   1166 │   │   │   logger.error(f"photos: {str(e)}")                                             │
│   1167                                                                                           │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:297   │
│ in __init__                                                                                      │
│                                                                                                  │
│    294 │   │   │   │   continue                                                                  │
│    295 │   │   │                                                                                 │
│    296 │   │   │   try:                                                                          │
│ ❱  297 │   │   │   │   self.images.append(GalleryImage(filename=pic, gallery=self))              │
│    298 │   │   │   except ImageExcluded:                                                         │
│    299 │   │   │   │   logger.debug(f"photos: Image {pic} excluded")                             │
│    300                                                                                           │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:328   │
│ in __init__                                                                                      │
│                                                                                                  │
│    325 │   │   │   dst=os.path.join(                                                             │
│    326 │   │   │   │   self._gallery.dst_dir, os.path.splitext(filename)[0].lower()              │
│    327 │   │   │   ),                                                                            │
│ ❱  328 │   │   │   specs=pelican_settings["PHOTO_GALLERY"],                                      │
│    329 │   │   )                                                                                 │
│    330 │   │   if img.is_excluded:                                                               │
│    331 │   │   │   raise ImageExcluded("Image excluded from gallery")                            │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:398   │
│ in __init__                                                                                      │
│                                                                                                  │
│    395 │   │   │   raise ValueError("Both spec and specs must not be provided")                  │
│    396 │   │                                                                                     │
│    397 │   │   #: The source image                                                               │
│ ❱  398 │   │   self.source_image = SourceImage.from_cache(src)                                   │
│    399 │   │   self.dst = dst                                                                    │
│    400 │   │                                                                                     │
│    401 │   │   self._height: Optional[int] = None                                                │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:831   │
│ in from_cache                                                                                    │
│                                                                                                  │
│    828 │   │   """Create a new SrcImage object or return it from the cache"""                    │
│    829 │   │   source_image = cls.image_cache.get(filename)                                      │
│    830 │   │   if source_image is None:                                                          │
│ ❱  831 │   │   │   source_image = cls(filename=filename)                                         │
│    832 │   │   │   cls.image_cache[filename] = source_image                                      │
│    833 │   │                                                                                     │
│    834 │   │   return source_image                                                               │
│                                                                                                  │
│ /home/harwood/Code/www_wasted/lib/python3.7/site-packages/pelican/plugins/photos/photos.py:787   │
│ in __init__                                                                                      │
│                                                                                                  │
│    784 │   │   self.filename = filename                                                          │
│    785 │   │   #: mime-type of the image                                                         │
│    786 │   │   self.mimetype, _ = mimetypes.guess_type(filename)                                 │
│ ❱  787 │   │   _, _, image_type = self.mimetype.partition("/")                                   │
│    788 │   │   #: type of the image. Mostly the second part of the mime-type (jpeg, png, ...)    │
│    789 │   │   self.type = image_type.lower()                                                    │
│    790                                                                                           │

**Comment by phibos** [comment] 2022-07-05 04:30
Looks like something went wrong with the mimetype detection. Do you have a broken image in the directory?

I will add an improved error handling.

**Comment by radoeka** [comment] 2022-08-09 08:33
I've the same.  It does not happen with photos 1.1.0.  It starts with photos-1.2.0

```<class 'pelican.plugins.photos.photos.CaptionCache'>
           DEBUG    photos: read_notes issue at file photos.py:144
                    /home/me/www/blog/content/media/town/home/captions.txt. Debug message:[Errno 2]
                    Bestand of map bestaat niet:
                    '/home/me/www/blog/content/media/town/home/captions.txt'
<class 'pelican.plugins.photos.photos.ExifCache'>
           DEBUG    photos: read_notes issue at file photos.py:144
                    /home/me/www/blog/content/media/town/home/exif.txt. Debug message:[Errno 2]
                    Bestand of map bestaat niet:
                    '/home/me/www/blog/content/media/town/home/exif.txt'
<class 'pelican.plugins.photos.photos.ExcludeCache'>
           DEBUG    photos: read_notes issue at file photos.py:144
                    /home/me/www/blog/content/media/town/home/blacklist.txt. Debug message:[Errno 2] 
                    Bestand of map bestaat niet:
                    '/home/me/www/blog/content/media/town/home/blacklist.txt'
```

**Comment by phibos** [comment] 2022-08-12 03:57
@radoeka
```
           DEBUG    photos: read_notes issue at file photos.py:144
                    /home/me/www/blog/content/media/town/home/captions.txt. Debug message:[Errno 2]
                    Bestand of map bestaat niet:
                    '/home/me/www/blog/content/media/town/home/captions.txt'
```
These are just debug messages. They help to identify why there are no captions. Because the captions file is missing. This is not a bug. What would you expect in this case to happen? Maybe we could improve the displayed information.

The output
```
<class 'pelican.plugins.photos.photos.ExcludeCache'>
```
should have been removed in the latest main branch.

**Comment by phibos** [comment] 2022-08-13 06:19
We are dealing with multiple issues at this point.

# Class message ✓

```
<class 'pelican.plugins.photos.photos.CaptionCache'>   
<class 'pelican.plugins.photos.photos.ExifCache'>
```
This was just a print() from a debug session and has already been fixed month ago in main.

# partition error ✓

```
CRITICAL AttributeError: 'NoneType' object has no attribute 'partition' init.py:566
```
This could happen if there was a subdirectory in the directory of the gallery. This has been fixed in #55 and will be in main soon. This also fixes some other issues if none image files are inside a gallery directory.

# message with exif.txt, captions.txt, ... files

I will change the output. But I'm not going to drop it from the debug output. If pelican is started with debug=1 I want to see as many information as there are. I someone only wants to see errors and warnings, don't start it in debug mode.

**Comment by radoeka** [comment] 2022-08-13 14:31
@phibos thanks a lot for your extensive explanation in the previous comment.

Looking forward to photos-1.4 that seems a good release (for me :) ).
Any idea when the release will be available?
( I had a look whether I would be able to cherry pick the fixes you mentioned above, but for now I don't see how to do that -> better wait for 1.4.0 if that does not take long ).

**Closed** 2022-08-15 04:11 UTC

**Comment by phibos** [comment] 2022-08-15 04:15
If have now also improved the exif.txt, captions.txt, ... file handling and merged the changes into main.

I try to fix at least #49 and #51 before releasing version 1.4 this week.

**Comment by radoeka** [comment] 2022-08-15 05:34
👍 :)

**Comment by radoeka** [comment] 2022-08-22 06:46
@phibos Milestone 'release-1.4.0' has no more open issues :)
Will you release photos soon?

**Comment by radoeka** [comment] 2022-09-03 09:19
@phibos is it possible to release 1.4.0, please.

**Comment by phibos** [comment] 2022-09-08 19:02
Version 1.4.0 has just been released. Sorry for the late response I was very busy in the last days.

**Comment by radoeka** [comment] 2022-09-08 19:55
Thanks, I'll install it one of these days.  It is still listed as 1.3.0 need to wait till the server have the newer version.
